from pathlib import Path

css = Path('thelounge-clean-chat.css')
s = css.read_text()

if 'v0.4.5-dev.1' not in s:
    s = s.replace('Maghuro - THE LOUNGE CLEAN CHAT v0.4.4', 'Maghuro - THE LOUNGE CLEAN CHAT v0.4.5-dev.1', 1)
    s = s.replace('--tlcc-version: "v0.4.4";', '--tlcc-version: "v0.4.5-dev.1";', 1)

s = s.replace('15. FULL FORMATTED CHANNEL TOPIC ON TOUCH DEVICES', '15. FULL FORMATTED CHANNEL TOPIC', 1)

old = '''@media (hover: hover) and (pointer: fine) {
    & #chat .header .topic {
        cursor: default;
    }
}
'''

new = '''@media (hover: hover) and (pointer: fine) {
    & #chat .header .topic {
        cursor: help;
    }

    /* Desktop: reveal the complete formatted topic on hover. The
       transparent ::before bridge keeps the header under the pointer
       after the topic itself becomes a fixed popup. */
    & #chat .header .topic:hover {
        position: fixed;
        top: 48px;
        left: 12px;
        right: 12px;
        z-index: 9999;
        display: block;
        width: auto;
        max-width: 900px;
        margin: 0 auto;
        min-width: 0;
        padding: 10px 12px;
        max-height: 45vh;
        overflow-x: hidden;
        overflow-y: auto;
        overscroll-behavior: contain;
        white-space: normal;
        word-break: normal;
        overflow-wrap: anywhere;
        line-height: 1.4;
        font-size: 13px;
        font-weight: 400;
        color: var(--body-color);
        background: var(--window-bg-color);
        border: 1px solid
            color-mix(in srgb, var(--body-color) 18%, transparent);
        border-radius: 8px;
        box-shadow: 0 6px 22px rgb(0 0 0 / 28%);
        mask-image: none;
        -webkit-mask-image: none;
        user-select: text;
        cursor: text;
    }

    & #chat .header .topic:hover::before {
        content: "";
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        height: 48px;
        background: transparent;
        pointer-events: auto;
    }
}
'''

if new not in s:
    if old not in s:
        raise SystemExit('desktop topic media block not found')
    s = s.replace(old, new, 1)

if s.count('{') != s.count('}'):
    raise SystemExit('CSS brace mismatch')

css.write_text(s)

readme = Path('README.md')
r = readme.read_text()
r = r.replace('**Current version:** v0.4.4  ', '**Current version:** v0.4.5-dev.1  ', 1)
r = r.replace('v0.4.4 is explicitly scoped', 'v0.4.5-dev.1 is explicitly scoped', 1)
r = r.replace('· Enhanced by TLCC v0.4.4', '· Enhanced by TLCC v0.4.5-dev.1', 1)
r = r.replace(
    '- Expands the real formatted channel topic on touch devices.\n- Contains touch-topic overscroll so the background chat is less likely to move while reading a long topic.',
    '- Expands the real formatted channel topic on touch devices and on desktop when hovering the topic.\n- Contains expanded-topic overscroll so the background chat is less likely to move while reading a long topic.',
    1,
)
old_topic = 'This does **not** modify the real IRC topic. It is generated by CSS in the local The Lounge UI and is useful for confirming which TLCC version the browser has actually received. On touch devices it remains visible when the formatted topic is expanded.'
new_topic = 'This does **not** modify the real IRC topic. It is generated by CSS in the local The Lounge UI and is useful for confirming which TLCC version the browser has actually received. The full formatted topic can be expanded on touch devices and, from v0.4.5-dev.1, on desktop by hovering the topic — useful on smaller monitors where the normal one-line header can truncate the TLCC marker.'
if old_topic in r:
    r = r.replace(old_topic, new_topic, 1)
readme.write_text(r)

changelog = Path('CHANGELOG.md')
c = changelog.read_text()
entry = '''## v0.4.5-dev.1 - 2026-09-11

### Changed

- Extended the full formatted channel-topic popup to desktop pointer devices: hovering the topic now reveals the same readable full-topic box already available on touch devices.
- Kept the normal compact one-line header unchanged until hover, so the desktop UI does not permanently consume extra vertical space.
- The popup includes the local `Enhanced by TLCC vX.X.X` marker, making the loaded TLCC version discoverable even on small monitors where the normal topic line truncates before the suffix.

### Notes

- Development preview only. Production `main` remains on v0.4.4 until this desktop interaction is verified.
- Thanks to **Captain Chungus**, whose small-monitor/very-long-topic discovery proved that “the marker exists” and “the human can actually see the marker” are, irritatingly, two different requirements. 🙃

'''
if entry not in c:
    anchor = '## v0.4.4 - 2026-09-11\n'
    if anchor not in c:
        raise SystemExit('CHANGELOG v0.4.4 anchor not found')
    c = c.replace(anchor, entry + anchor, 1)
changelog.write_text(c)

print('OK: v0.4.5-dev.1 desktop topic popup staged')
