name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - thelounge-clean-chat.css
      - .github/workflows/purge-jsdelivr.yml
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  purge-jsdelivr:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js LTS
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Purge TLCC from jsDelivr
        uses: List-KR/jsdelivr-purge@7.0.1
        with:
          urls: |
            /gh/maghuro/thelounge-clean-chat@main/thelounge-clean-chat.css
          url-mode: overwrite
